services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: mydatabase
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: react_frontend
  #   ports:
  #     - '3000:5173'
  #   env_file:
  #     - .env
  #   environment:
  #     - VITE_API_URL=http://backend:3001
  #   networks:
  #     - app-network
  #   depends_on:
  #     - db
  #     - backend

  # backend:
  #   build:
  #     context: ./backend
  #   container_name: nestjs_backend
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:mypassword@db:5432/mydatabase
  #   ports:
  #     - '3001:3001'
  #   env_file:
  #     - .env
  #   networks:
  #     - app-network
  #   depends_on:
  #     - db

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
